apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-minikube
  name: hello-minikube
spec:
  selector:
    app: hello-minikube
  ports:
    - NodePort: 30410
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: NodePort